# Stage 1: Build the application using Maven
ARG AND_DOCKER_PROXY_REGISTRY_NAME

FROM $AND_DOCKER_PROXY_REGISTRY_NAME/maven:3.9-eclipse-temurin-21 AS build
ARG JAVA_ACCESS_TOKEN
ENV JAVA_ACCESS_TOKEN=$JAVA_ACCESS_TOKEN
WORKDIR /app
COPY pom.xml .
COPY settings.xml .
COPY mvnw .
COPY .mvn .mvn
COPY config ./config
COPY src ./src
RUN mkdir ~/.m2 && chmod -R 777 ~/.m2
RUN mv settings.xml ~/.m2 && mvn clean install $MAVEN_CLI_OPTS -Dmaven.test.skip
RUN mvn dependency:go-offline
RUN mvn package -DskipTests

# Stage 2: Create the final, smaller image
FROM $AND_DOCKER_PROXY_REGISTRY_NAME/eclipse-temurin:21-jre-jammy
RUN apt-get update && \
    apt-get install -y curl && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*
WORKDIR /app
COPY --from=build /app/target/*.jar ./app.jar
EXPOSE 8080
ENTRYPOINT ["java", "-jar", "app.jar"]
