ARG AND_DOCKER_PROXY_REGISTRY_NAME=docker.io

FROM ${AND_DOCKER_PROXY_REGISTRY_NAME}/python:3.12.6-slim AS builder

RUN pip install "poetry>=2.0.0"
RUN poetry self add poetry-plugin-export

WORKDIR /app

COPY pyproject.toml poetry.lock ./
RUN poetry export -f requirements.txt --output requirements.txt

FROM ${AND_DOCKER_PROXY_REGISTRY_NAME}/python:3.12.6-slim

WORKDIR /app

COPY --from=builder /app/requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY . .


CMD ["gunicorn", "app.main:app", "--workers", "4", "--worker-class", "uvicorn.workers.UvicornWorker", "--bind", "0.0.0.0:8002"]

